name: Auto Commit

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  auto-commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config user.name "bekishh"
          git config user.email "beknazarzholdoshbekov1@gmail.com"

      - name: Make changes
        run: |
          echo "$(date) - Auto commit executed" >> auto_update.txt
          git add auto_update.txt
          git commit -m "Auto Commit - $(date)" || echo "No changes to commit"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/bekishh/push-flow.git
          git push
