name: Auto Commit

on:
  schedule:
    - cron: "*/15 * * * *" # Каждые 15 минут

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update file
        run: |
          echo "$(date) - Auto update" >> auto_update.txt

      - name: Commit changes
        run: |
          git config user.name "YourGitHubUsername"
          git config user.email "your-email@example.com"
          git add .
          git commit -m "Auto commit on $(date)" || echo "No changes to commit"

      - name: Push changes
        run: git push
